# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-latest
          - macos-13
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
        gemfile:
          - openssl_2_2
          - openssl_2_1
          - openssl_3_0
          - openssl_3_1
          - openssl_3_2
        exclude:
          - ruby: '2.4'
            gemfile: openssl_3_0
          - ruby: '2.5'
            gemfile: openssl_3_0
          - ruby: '2.4'
            gemfile: openssl_3_1
          - ruby: '2.5'
            gemfile: openssl_3_1
          - ruby: '2.4'
            gemfile: openssl_3_2
          - ruby: '2.5'
            gemfile: openssl_3_2
          - ruby: '2.6'
            gemfile: openssl_3_2
          - ruby: '3.1'
            gemfile: openssl_2_2
            os: macos-13
          - ruby: '3.1'
            gemfile: openssl_2_1
            os: macos-13
          - ruby: '3.2'
            gemfile: openssl_2_2
            os: macos-13
          - ruby: '3.2'
            gemfile: openssl_2_1
            os: macos-13
          - ruby: '3.2'
            gemfile: openssl_2_2
            os: windows-latest
          - ruby: '3.2'
            gemfile: openssl_2_1
            os: windows-latest
          - ruby: '3.3'
            gemfile: openssl_2_2
            os: macos-13
          - ruby: '3.3'
            gemfile: openssl_2_1
            os: macos-13
          - ruby: '3.3'
            gemfile: openssl_2_2
            os: windows-latest
          - ruby: '3.3'
            gemfile: openssl_2_1
            os: windows-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v4

    - run: rm Gemfile.lock

    - id: cache-openssl
      if: matrix.os == 'ubuntu-22.04' && steps.cache-openssl.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: ~/openssl
        key: openssl-ubuntu-22.04-openssl-1.1.1w-default

    - name: Compile OpenSSL library
      if: matrix.os == 'ubuntu-22.04' && steps.cache-openssl.outputs.cache-hit != 'true'
      run: |
        # Enable Bash debugging option temporarily for debugging use.
        set -x
        mkdir -p tmp/build-openssl && cd tmp/build-openssl
        OPENSSL_COMMIT=$(echo openssl-1.1.1w | sed -e 's/^openssl-/OpenSSL_/' | sed -e 's/\./_/g')
        git clone -b $OPENSSL_COMMIT --depth 1 https://github.com/openssl/openssl.git .
        echo "Git commit: $(git rev-parse HEAD)"
        # shared is required for 1.0.x.
        ./Configure --prefix=$HOME/openssl --libdir=lib shared linux-x86_64
        make depend && make -j4 && make install_sw

    - name: configure openssl dir
      run:  echo 'RUBY_CONFIGURE_OPTS="--with-openssl-dir=$HOME/openssl"' >> $GITHUB_ENV

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        self-hosted: true

    - run: bundle exec rake
