# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop -f github
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest
          - macos-13
        ruby:
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
        gemfile:
          - openssl_2_2
          - openssl_2_1
          - openssl_3_0
          - openssl_3_1
          - openssl_3_2
          - openssl_3_3
        exclude:
          - ruby: '2.4'
            gemfile: openssl_3_0
          - ruby: '2.5'
            gemfile: openssl_3_0
          - ruby: '2.4'
            gemfile: openssl_3_1
          - ruby: '2.5'
            gemfile: openssl_3_1
          - ruby: '2.4'
            gemfile: openssl_3_2
          - ruby: '2.5'
            gemfile: openssl_3_2
          - ruby: '2.6'
            gemfile: openssl_3_2
          - ruby: '2.4'
            gemfile: openssl_3_3
          - ruby: '2.5'
            gemfile: openssl_3_3
          - ruby: '2.6'
            gemfile: openssl_3_3
          - ruby: '3.1'
            gemfile: openssl_2_2
            os: macos-13
          - ruby: '3.1'
            gemfile: openssl_2_1
            os: macos-13
          - ruby: '3.2'
            gemfile: openssl_2_2
            os: macos-13
          - ruby: '3.2'
            gemfile: openssl_2_1
            os: macos-13
          - ruby: '3.2'
            gemfile: openssl_2_2
            os: windows-latest
          - ruby: '3.2'
            gemfile: openssl_2_1
            os: windows-latest
          - ruby: '3.3'
            gemfile: openssl_2_2
            os: macos-13
          - ruby: '3.3'
            gemfile: openssl_2_1
            os: macos-13
          - ruby: '3.3'
            gemfile: openssl_2_2
            os: windows-latest
          - ruby: '3.3'
            gemfile: openssl_2_1
            os: windows-latest
          - ruby: '3.4'
            gemfile: openssl_2_2
            os: macos-13
          - ruby: '3.4'
            gemfile: openssl_2_1
            os: macos-13
          - ruby: '3.4'
            gemfile: openssl_2_2
            os: windows-latest
          - ruby: '3.4'
            gemfile: openssl_2_1
            os: windows-latest
          - ruby: '2.4'
            os: ubuntu-20.04
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v4

    - run: rm Gemfile.lock

    - name: Install OpenSSL
      if: matrix.os == 'ubuntu-20.04'
      uses: ./.github/actions/install-openssl
      with:
        version: "1.1.1w"
        os: ${{ matrix.os }}

    - uses: ruby/setup-ruby@v1
      if: matrix.os != 'ubuntu-20.04'
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Manually set up Ruby
      if: matrix.os == 'ubuntu-20.04'
      uses: ./.github/actions/install-ruby
      with:
        version: ${{ matrix.ruby }}
        os: ${{ matrix.os }}

    - run: bundle exec rspec
